pool:
    vmImage: 'ubuntu-latest'

schedules:
- cron: "0 * * * *"
  branches:
    include: 
      - master
  always: "true"

jobs:
  - job: renovate
    displayName: Renovate
    steps:
      - task: Npm@1
        displayName: NPM Install
        inputs:
          command: 'install'
      - task: Bash@3
        displayName: renovate.sh
        inputs:
          filePath: 'renovate.sh'
          arguments: '$(System.AccessToken)'