pool:
    vmImage: 'ubuntu-latest'

schedules:
- cron: "0 * * * *"
  branches:
    include: 
      - master
  always: "true"

jobs:
  - job: renovate
    displayName: Renovate
    steps:
      - task: Cache@2
        displayName: Cache npm
        inputs:
          key: 'npm | "$(Agent.OS)" | package-lock.json'
          path: ./node_modules
          cacheHitVar: CACHE_RESTORED

      - task: Npm@1
        displayName: Npm install
        condition: ne(variables.CACHE_RESTORED, 'true')
        inputs:
          command: 'install'

      - task: Bash@3
        displayName: Run renovate
        inputs:
          targetType: 'inline'
          script: |
            export RENOVATE_CONFIG_FILE="./renovate-config.js"
            export RENOVATE_TOKEN="$(System.AccessToken)"
            export RENOVATE_ENDPOINT="$(System.CollectionUri)"
            node ./node_modules/renovate/dist/renovate --autodiscover