pool:
    vmImage: 'ubuntu-latest'

schedules:
- cron: "0 * * * *"
  branches:
    include: 
      - master
  always: "true"

jobs:
  - job: renovate
    displayName: Renovate
    steps:
      - task: Npm@1
        displayName: NPM Install
        inputs:
          command: 'install'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            export RENOVATE_CONFIG_FILE="./renovate-config.js"
            export RENOVATE_TOKEN="$(System.AccessToken)"
            renovate --autodiscover